services:
  db:
    image: bitnami/postgresql:10.20.0-debian-10-r52
    restart: always
    ports:
      - $POSTGRES_PORT:5432
    env_file:
      - ./.env

  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tashkent"
    restart: always
